# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec2681d47bd9a6b48457abda41827cc3bf69ccd07d04fe954735b87686fbc477cb7e0e2df52d8a2adba1e2d911908662dc0b64bb2adc6149ecf6e8d7f5f79b6f

test:
  secret_key_base: 0b05012e8386009b9a3788d7d3436fc1806eae578720d00478659cf17cce32e30038ecc66a140d8cb238d2eb721605790a790b41f40dc6d312dee2532792f0be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
